### ISSUE TITLE
Auto sku with sizes

### ISSUE THREAD

**Issue by fwegberts** [schmengler/AutoSKU#1]
Hi,

Normally when you at a t-shirt with different sizes, Magento will make sku's like this:

123-L
123-XL
123-XXL

With your extension it does:
123
124
125

Is there a solution for this?

**Comment by schmengler** [comment]
This happens in `Mage_Adminhtml_Catalog_ProductController`:

```
        if ($product->getSkuAutogenerate()) {
            $product->setSku($configurableProduct->getSku() . '-' . implode('-', $autogenerateOptions));
        }
```

So the extension would need to take `getSkuAutogenerate()` into account (and in this case, not generate the SKU on its own).

**Comment by fwegberts** [comment]
Can you fix this for me?
