### ISSUE TITLE
Fatal error: Class 'SSE_AutoSku_Model_Resource_Setup' not found

### ISSUE THREAD

**Issue by JamesSimpson** [schmengler/AutoSKU#4]
Just tried installing this on the latest version of Magento and I get the following error:

Fatal error: Class 'SSE_AutoSku_Model_Resource_Setup' not found in /home/developmentproma/public_html/includes/src/Mage_Core_Model_Resource_Setup.php on line 234

Cache flushed, Compilation off.

**Comment by schmengler** [comment]
Cannot reproduce it, but the path `includes/src/Mage_Core_Model_Resource_Setup.php` does not look right. You probably are still using compilation
